console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#282828'
  blue = '#458588'
  green = '#98971a'
  orange = '#d79921'
  red = '#cc241d'
  white = '#ebdbb2'
  yellow = '#fabd2f'

[secondary_prompt]
  template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
  foreground = 'p:black'
  background = 'transparent'

[transient_prompt]
  template = '<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> '
  foreground = 'p:black'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
    foreground = 'p:black'
    background = 'p:yellow'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    template = '  <b>{{ path .Path .Location }}</b> '
    foreground = 'p:orange'
    powerline_symbol = ''
    background = 'p:black'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template = '  <b>{{ .HEAD }}</b>{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:green'
    powerline_symbol = ''
    background = 'p:black'
    type = 'git'
    style = 'powerline'
  foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:green{{ end }}', '{{ if eq .Background "p:yellow" }}p:black{{ end }}']
  background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}']

    [blocks.segments.properties]
      branch_template = '{{ trunc 25 .Branch }}'
      fetch_status = true
      fetch_upstream_icon = false

  [[blocks.segments]]
    template = '  '
    foreground = 'p:yellow'
    powerline_symbol = ''
    background = 'p:black'
    type = 'root'
    style = 'powerline'

  [[blocks.segments]]
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    foreground = 'p:blue'
    background = 'p:black'
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    template = ' <b>{{ .Version }}</b>'
    foreground = 'p:green'
    background = 'transparent'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false
      fetch_version = true

  [[blocks.segments]]
    template = ' <b>{{ .Version }}</b>'
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true
      fetch_virtual_env = true

  [[blocks.segments]]
    template = ' <b>{{ .Version }}</b>'
    foreground = 'p:blue'
    background = 'transparent'
    type = 'rust'
    style = 'plain'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    template = 'at <p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'
    foreground = 'p:white'
    background = 'transparent'
    type = 'time'
    style = 'plain'

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  foreground = 'p:white'
  background = 'p:orange'
  type = 'aws'
  style = 'diamond'
  tips = ['aws']

  [tooltips.properties]
    display_default = true

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '
  foreground = 'p:white'
  background = 'p:blue'
  type = 'az'
  style = 'diamond'
  tips = ['az']

  [tooltips.properties]
    display_default = true
